# Generated by Django 5.2.15 on 2026-07-01 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='pengajar'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='matkul'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.coursecontent', verbose_name='induk'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='matkul'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='siswa'),
        ),
    ]
