# Generated by Django 5.2.15 on 2026-07-02 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='selesai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='waktu selesai')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent', verbose_name='konten')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='siswa')),
            ],
            options={
                'verbose_name': 'Progres Siswa',
                'verbose_name_plural': 'Progres Siswa',
                'unique_together': {('user', 'content')},
            },
        ),
    ]
